[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
nft_staking = "nftmapxi1xxp8F4TiU3cZ7xxEd1kFcT5aSnpRZaqa3U"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
